spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/avisdevol
    username: avisdevol
    password: #Password
    driver-class-name: org.postgresql.Driver
  mvc:
    servlet:
      path: /api
      
  jpa:
    hibernate:
      ddl-auto: update         
    show-sql: true            
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true       
  application:
    name:avisdevol

# Default Swagger config
springdoc:
  packages-to-scan: fr.florianrenaud.avisdevol.rest
  swagger-ui:
    enabled: true
    path: /swagger
    tagsSorter: alpha
    operationsSorter: method
    docExpansion: list
    defaultModelRendering: example
    defaultModelsExpandDepth: -1
    displayRequestDuration: true
    filter: true
    csrf:
      enabled: true
    syntaxHighlight:
      theme: arta
  api-docs:
    enabled: true
    path: /v3/api-docs

debug: false
